"use client";
import { useEffect, useState } from "react";
import { Heart, MessageCircle, Quote, Send, Star } from "lucide-react";
import SiteHeader from "@/components/SiteHeader";
import { createSupabaseBrowserClient } from "@/lib/supabase-browser";
import { getCurrentUser, postComment, toggleReviewLike } from "@/lib/storybook";

type Review={id:string;name:string;book:string;rating:number;text:string;likes:number;time:string;liked:boolean};
const fallback:Review[]=[{id:"demo-1",name:"Amina W.",book:"Things Fall Apart",rating:5,text:"Achebe makes culture feel alive. The final chapters stayed with me long after I closed the book.",likes:128,time:"18 min ago",liked:false},{id:"demo-2",name:"Brian K.",book:"Deep Work",rating:4,text:"Protecting focused time completely changed how I study and build.",likes:84,time:"2 hrs ago",liked:false},{id:"demo-3",name:"Maya R.",book:"Atomic Habits",rating:5,text:"The system-first approach is the real gem. Small actions finally feel sustainable.",likes:203,time:"Yesterday",liked:false}];

export default function Community(){
 const [reviews,setReviews]=useState<Review[]>(fallback); const [loading,setLoading]=useState(true); const [commenting,setCommenting]=useState<string|null>(null); const [comment,setComment]=useState(""); const [message,setMessage]=useState("");
 useEffect(()=>{load()},[]);
 async function load(){const supabase=createSupabaseBrowserClient(); if(!supabase){setLoading(false);return;} const user=await getCurrentUser(); const {data,error}=await supabase.from("reviews").select("id,rating,body,created_at,books(title),profiles(display_name,username)").order("created_at",{ascending:false}).limit(30); if(error||!data){setLoading(false);return;} const ids=data.map((x:any)=>x.id); const {data:likes}=ids.length?await supabase.from("review_likes").select("review_id,user_id").in("review_id",ids):{data:[]}; const rows=data.map((x:any)=>({id:x.id,name:x.profiles?.display_name||x.profiles?.username||"Reader",book:x.books?.title||"Book",rating:x.rating,text:x.body,likes:(likes||[]).filter((l:any)=>l.review_id===x.id).length,time:new Date(x.created_at).toLocaleDateString(undefined,{month:"short",day:"numeric"}),liked:!!user&&(likes||[]).some((l:any)=>l.review_id===x.id&&l.user_id===user.id)})); setReviews(rows); setLoading(false);}
 async function like(item:Review){try{await toggleReviewLike(item.id,item.liked);setReviews(v=>v.map(x=>x.id===item.id?{...x,liked:!x.liked,likes:x.likes+(x.liked?-1:1)}:x));}catch(e:any){setMessage(e.message||"Sign in to like reviews.")}}
 async function sendComment(id:string){if(!comment.trim())return;try{await postComment(id,comment.trim());setComment("");setCommenting(null);setMessage("Comment posted ✓");}catch(e:any){setMessage(e.message||"Sign in to comment.")}}
 return <><SiteHeader/><main className="mx-auto max-w-6xl px-5 py-14 sm:px-8 lg:py-20"><div className="max-w-3xl"><p className="eyebrow">Reader community</p><h1 className="section-title mt-2">Good books deserve good conversations.</h1><p className="mt-6 text-base leading-7 text-[var(--muted)]">Reviews here are personal, imperfect and thoughtful. Read what other people noticed — then add your own voice.</p></div>{message&&<div className="mt-6 rounded-2xl bg-accent-soft p-3 text-xs text-accent">{message}</div>}<div className="mt-12 grid gap-5">{loading?<div className="paper-card p-8 text-sm text-[var(--muted)]">Loading the reading room…</div>:reviews.map(x=><article key={x.id} className="paper-card p-6 sm:p-8"><div className="flex gap-4"><div className="grid size-12 shrink-0 place-items-center rounded-full bg-accent-soft text-xs font-black text-accent">{x.name.split(" ").map(n=>n[0]).join("")}</div><div className="flex-1"><div className="flex flex-wrap items-center justify-between gap-3"><div><b>{x.name}</b><span className="mx-2 text-[var(--muted)]">reviewed</span><b>{x.book}</b></div><span className="text-xs text-[var(--muted)]">{x.time}</span></div><div className="mt-2 flex gap-0.5">{Array.from({length:5}).map((_,i)=><Star key={i} size={13} fill="currentColor" className={i<x.rating?"text-accent":"text-black/10"}/>)}</div><p className="mt-5 max-w-3xl text-sm leading-7 opacity-70">“{x.text}”</p><div className="mt-5 flex gap-4 text-xs opacity-55"><button onClick={()=>like(x)} className={x.liked?"font-bold text-accent":""}><Heart size={14} className="mr-1 inline" fill={x.liked?"currentColor":"none"}/> {x.likes}</button><button onClick={()=>setCommenting(commenting===x.id?null:x.id)}><MessageCircle size={14} className="mr-1 inline"/> Comment</button></div>{commenting===x.id&&<div className="mt-4 flex gap-2"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a thoughtful comment…" className="min-w-0 flex-1 rounded-2xl border border-[var(--line)] bg-[var(--card)] px-4 py-3 text-sm outline-none"/><button onClick={()=>sendComment(x.id)} className="share-button rounded-2xl px-4"><Send size={15}/></button></div>}</div></div></article>)}</div><div className="paper-card mt-6 grid gap-4 bg-[var(--ink)] p-8 text-[var(--paper)]"><Quote className="text-accent"/><p className="serif max-w-2xl text-2xl leading-tight">The best recommendation is the one that makes you want to turn the page.</p></div></main></>}
