import {notFound} from "next/navigation";
import {ArrowLeft,Quote,Star} from "lucide-react";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import BookActions from "@/components/BookActions";
import {books,tones} from "@/lib/books";

export function generateStaticParams(){return books.map(book=>({id:book.id}));}

export default async function BookPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params; const book=books.find(x=>x.id===id); if(!book)return notFound();
 return <><SiteHeader/><main className="mx-auto max-w-6xl px-5 py-12 sm:px-8 lg:py-20"><Link href="/discover" className="text-xs font-bold text-[var(--muted)]"><ArrowLeft size={14} className="mr-1 inline"/> Back to discovery</Link><section className="mt-10 grid gap-12 lg:grid-cols-[360px_1fr] lg:items-center"><div className={`book-cover mx-auto h-[480px] w-[320px] rounded-[6px_24px_24px_6px] bg-gradient-to-br ${tones[book.tone]} p-9 text-white`}><div className="flex h-full flex-col justify-between"><span className="text-[9px] font-black tracking-[.25em] opacity-60">STORYBOOK EDITION</span><div><p className="mb-4 text-[10px] uppercase tracking-[.2em] opacity-55">{book.genre}</p><h1 className="text-5xl font-black leading-[.84] tracking-[-.06em]">{book.title}</h1><p className="mt-5 text-sm opacity-65">{book.author}</p></div><span className="text-[10px] opacity-45">{book.year} · {book.pages} pages</span></div></div><div><p className="eyebrow">Book profile</p><h2 className="mt-3 text-5xl font-black leading-[.9] tracking-[-.06em]">{book.title}</h2><p className="mt-3 text-lg text-[var(--muted)]">by {book.author}</p><div className="mt-7 flex items-center gap-4"><span className="rounded-full bg-[var(--card)] px-4 py-2 text-sm font-bold"><Star size={14} className="mr-1 inline" fill="currentColor"/> {book.rating}</span><span className="text-xs text-[var(--muted)]">{book.reviews.toLocaleString()} community reviews</span></div><p className="mt-8 max-w-2xl text-base leading-7 opacity-65">{book.blurb} This StoryBook edition is part of the community shelf for readers who want to go deeper, compare perspectives and keep the conversation alive.</p><BookActions bookId={book.id}/><div className="mt-12 rounded-[26px] bg-[var(--ink)] p-7 text-[var(--paper)]"><Quote className="text-accent"/><p className="serif mt-5 text-xl leading-7 opacity-85">“{book.quote}”</p></div></div></section></main></>}
