"use client";

import { useEffect, useMemo, useState } from "react";
import { BookOpen, Bookmark, Check, ChevronRight, Flame, Heart, Library, LogIn, Menu, MessageCircle, Plus, Search, Sparkles, Star, Trophy, UserRound, Users, X } from "lucide-react";
import { toast } from "sonner";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/client";

type Book = { id:string; title:string; author:string; genre:string; description:string; rating:number; reviews:number; cover:string; color:string };
type Review = { id:string; user:string; initials:string; book:string; rating:number; text:string; likes:number; comments:number; time:string };

const seedBooks:Book[] = [
 {id:"atomic-habits",title:"Atomic Habits",author:"James Clear",genre:"Self-growth",description:"Tiny changes, remarkable results. A practical guide to building better habits.",rating:4.8,reviews:1824,cover:"AH",color:"linear-gradient(145deg,#172554,#7c3aed)"},
 {id:"alchemist",title:"The Alchemist",author:"Paulo Coelho",genre:"Fiction",description:"A timeless story about following a dream, listening to your heart and finding meaning.",rating:4.7,reviews:1420,cover:"TA",color:"linear-gradient(145deg,#422006,#ea580c)"},
 {id:"deep-work",title:"Deep Work",author:"Cal Newport",genre:"Productivity",description:"Rules for focused success in a distracted world.",rating:4.6,reviews:987,cover:"DW",color:"linear-gradient(145deg,#083344,#0891b2)"},
 {id:"things-fall-apart",title:"Things Fall Apart",author:"Chinua Achebe",genre:"African literature",description:"A landmark novel about culture, identity, change and the cost of pride.",rating:4.9,reviews:2210,cover:"TFA",color:"linear-gradient(145deg,#052e16,#16a34a)"},
 {id:"design-of-everyday-things",title:"The Design of Everyday Things",author:"Don Norman",genre:"Design",description:"A classic exploration of human-centered design and why everyday products work—or fail.",rating:4.7,reviews:763,cover:"DO",color:"linear-gradient(145deg,#3b0764,#c026d3)"},
 {id:"psychology-money",title:"The Psychology of Money",author:"Morgan Housel",genre:"Business",description:"Timeless lessons on wealth, greed, risk and behavior.",rating:4.8,reviews:1106,cover:"PM",color:"linear-gradient(145deg,#172554,#2563eb)"},
 {id:"start-with-why",title:"Start With Why",author:"Simon Sinek",genre:"Business",description:"Discover the purpose that inspires people and creates lasting momentum.",rating:4.5,reviews:641,cover:"SW",color:"linear-gradient(145deg,#431407,#f97316)"},
 {id:"the-power-of-now",title:"The Power of Now",author:"Eckhart Tolle",genre:"Mindfulness",description:"A guide to presence, awareness and stepping outside the noise of the mind.",rating:4.4,reviews:901,cover:"PN",color:"linear-gradient(145deg,#134e4a,#14b8a6)"}
];
const seedReviews:Review[]=[
 {id:"r1",user:"Amina W.",initials:"AW",book:"Things Fall Apart",rating:5,text:"Achebe makes culture feel alive. The final chapters stayed with me long after I closed the book.",likes:128,comments:19,time:"18 min ago"},
 {id:"r2",user:"Brian K.",initials:"BK",book:"Deep Work",rating:4,text:"The ideas are simple, but actually protecting focused time changed how I study and build.",likes:84,comments:11,time:"2 hrs ago"},
 {id:"r3",user:"Maya R.",initials:"MR",book:"Atomic Habits",rating:5,text:"I stopped trying to reinvent myself overnight. The system-first approach is the real gem.",likes:203,comments:27,time:"Yesterday"}
];
const genres=["All","Fiction","Self-growth","African literature","Productivity","Design","Business","Mindfulness"];

export default function Home(){
 const [books,setBooks]=useState(seedBooks); const [reviews,setReviews]=useState(seedReviews); const [query,setQuery]=useState(""); const [genre,setGenre]=useState("All");
 const [saved,setSaved]=useState<string[]>([]); const [liked,setLiked]=useState<string[]>([]); const [authOpen,setAuthOpen]=useState(false); const [shareOpen,setShareOpen]=useState(false); const [mobileOpen,setMobileOpen]=useState(false);
 const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [authMode,setAuthMode]=useState<"signin"|"signup">("signin"); const [user,setUser]=useState<any>(null); const [loading,setLoading]=useState(false);
 const configured=isSupabaseConfigured();

 useEffect(()=>{ if(!configured) return; const supabase=createClient(); supabase.auth.getUser().then(({data})=>setUser(data.user)); const {data:sub}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null)); supabase.from("books").select("id,title,author,genre,description,rating,review_count,cover_url").order("created_at",{ascending:false}).limit(24).then(({data})=>{if(data?.length)setBooks(data.map((b:any,i)=>({...b,reviews:b.review_count??0,cover:b.title.slice(0,2).toUpperCase(),color:seedBooks[i%seedBooks.length].color,rating:b.rating??4.5}))) }); return()=>sub.subscription.unsubscribe(); },[configured]);

 const filtered=useMemo(()=>books.filter(b=>(genre==="All"||b.genre===genre)&&`${b.title} ${b.author} ${b.genre}`.toLowerCase().includes(query.toLowerCase())),[books,genre,query]);
 const toggleSave=async(id:string)=>{setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]); if(configured&&user){const supabase=createClient(); if(saved.includes(id)) await supabase.from("shelves").delete().eq("user_id",user.id).eq("book_id",id); else await supabase.from("shelves").upsert({user_id:user.id,book_id:id,shelf:"want_to_read"});} };
 const toggleLike=async(id:string)=>{setLiked(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]); setReviews(rs=>rs.map(r=>r.id===id?{...r,likes:r.likes+(liked.includes(id)?-1:1)}:r)); if(configured&&user){const supabase=createClient(); if(liked.includes(id)) await supabase.from("review_likes").delete().eq("user_id",user.id).eq("review_id",id); else await supabase.from("review_likes").insert({user_id:user.id,review_id:id});} };
 const submitAuth=async(e:React.FormEvent)=>{e.preventDefault(); if(!configured){toast("Connect Supabase to enable accounts.");return;} setLoading(true); const supabase=createClient(); const result=authMode==="signin"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password}); setLoading(false); if(result.error)toast.error(result.error.message); else {toast.success(authMode==="signin"?"Welcome back!":"Account created — check your email to confirm.");setAuthOpen(false);} };
 const submitReview=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault(); if(!user){setShareOpen(false);setAuthOpen(true);toast("Sign in first to publish to the community.");return;} const fd=new FormData(e.currentTarget); const title=String(fd.get("title")); const author=String(fd.get("author")); const text=String(fd.get("text")); const rating=Number(fd.get("rating")); setLoading(true); if(configured){const supabase=createClient(); let book=books.find(b=>b.title.toLowerCase()===title.toLowerCase()); if(!book){const {data,error}=await supabase.from("books").insert({title,author,genre:String(fd.get("genre")),description:text,rating}).select().single(); if(error){toast.error(error.message);setLoading(false);return;} book={id:data.id,title:data.title,author:data.author,genre:data.genre,description:data.description??"",rating:data.rating??rating,reviews:0,cover:title.slice(0,2).toUpperCase(),color:"linear-gradient(145deg,#312e81,#8b5cf6)"};setBooks(b=>[book!,...b]);} const {error}=await supabase.from("reviews").insert({book_id:book.id,user_id:user.id,rating,body:text}); if(error){toast.error(error.message);setLoading(false);return;} } setReviews(r=>[{id:`local-${Date.now()}`,user:user.email?.split("@")[0]??"Reader",initials:"R",book:title,rating,text,likes:0,comments:0,time:"Just now"},...r]); setLoading(false);setShareOpen(false);toast.success("Your review is live ✦"); };
 const signOut=async()=>{if(configured)await createClient().auth.signOut();setUser(null);toast("Signed out");};
 return <div className="min-h-screen selection:bg-violet-500/30">
  <header className="glass sticky top-0 z-50"><div className="mx-auto flex h-18 max-w-7xl items-center gap-7 px-4 sm:px-6">
   <a href="#top" className="flex items-center gap-3 font-black tracking-tight"><span className="grid size-10 place-items-center rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-400 shadow-lg shadow-violet-900/30"><BookOpen size={20}/></span><span className="text-lg">Story<span className="text-violet-300">Book</span></span></a>
   <nav className="hidden items-center gap-6 text-sm text-slate-400 md:flex"><a className="hover:text-white" href="#discover">Discover</a><a className="hover:text-white" href="#community">Community</a><a className="hover:text-white" href="#library">Library</a><a className="hover:text-white" href="#challenges">Challenges</a></nav>
   <div className="ml-auto flex items-center gap-2">{user?<button onClick={signOut} className="hidden rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-slate-300 hover:bg-white/10 sm:block">Sign out</button>:<button onClick={()=>setAuthOpen(true)} className="hidden rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-slate-300 hover:bg-white/10 sm:flex items-center gap-2"><LogIn size={16}/> Sign in</button>}<button onClick={()=>setShareOpen(true)} className="hidden rounded-xl bg-white px-4 py-2 text-sm font-bold text-slate-950 hover:bg-slate-200 sm:block"><Plus size={16} className="inline mr-1"/> Share</button><button onClick={()=>setMobileOpen(!mobileOpen)} className="rounded-xl border border-white/10 p-2 md:hidden"><Menu size={19}/></button></div>
  </div>{mobileOpen&&<div className="border-t border-white/10 px-5 py-4 md:hidden"><div className="grid gap-3 text-sm text-slate-300"><a href="#discover" onClick={()=>setMobileOpen(false)}>Discover</a><a href="#community" onClick={()=>setMobileOpen(false)}>Community</a><a href="#library" onClick={()=>setMobileOpen(false)}>Library</a><a href="#challenges" onClick={()=>setMobileOpen(false)}>Challenges</a><button onClick={()=>{setMobileOpen(false);setShareOpen(true)}} className="mt-1 rounded-xl bg-white px-4 py-3 font-bold text-slate-950">Share a book</button></div></div>}</header>

  <main id="top">
   <section className="mx-auto grid max-w-7xl gap-10 px-4 pb-10 pt-14 sm:px-6 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:pt-24">
    <div className="fade-up"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-violet-400/20 bg-violet-400/10 px-3 py-1.5 text-xs font-semibold text-violet-200"><Sparkles size={14}/> A social home for curious readers</div><h1 className="max-w-3xl text-5xl font-black leading-[.98] tracking-[-.055em] sm:text-7xl">Read deeply.<br/><span className="gradient">Share boldly.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg">Discover your next great book, exchange thoughtful reviews, build a reading habit and find people who love stories as much as you do.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#discover" className="rounded-2xl bg-white px-5 py-3 text-sm font-extrabold text-slate-950 shadow-xl shadow-white/5 hover:-translate-y-0.5">Explore books <ChevronRight className="inline" size={17}/></a><button onClick={()=>setShareOpen(true)} className="rounded-2xl border border-white/10 bg-white/5 px-5 py-3 text-sm font-bold text-white hover:bg-white/10">Share your story</button></div><div className="panel mt-8 flex max-w-2xl items-center gap-2 rounded-2xl p-2"><Search className="ml-2 text-slate-500" size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search titles, authors or genres..." className="min-w-0 flex-1 bg-transparent px-2 py-2.5 text-sm outline-none placeholder:text-slate-600"/><span className="hidden rounded-xl bg-white/5 px-3 py-2 text-xs text-slate-500 sm:block">⌘ K</span></div></div>
    <div className="relative mx-auto h-[360px] w-full max-w-[480px] lg:h-[470px]"><div className="absolute inset-12 rounded-full bg-violet-600/20 blur-3xl"/><div className="absolute right-0 top-8 h-24 w-24 rounded-3xl border border-cyan-300/20 bg-cyan-300/10 blur-[1px]"/><div className="absolute bottom-8 left-2 h-16 w-16 rounded-full bg-lime-300/10"/>
      <div className="absolute left-1/2 top-1/2 h-[310px] w-[205px] -translate-x-1/2 -translate-y-1/2 rotate-[-8deg] rounded-r-3xl rounded-l-md border border-white/15 bg-gradient-to-br from-slate-900 via-violet-800 to-violet-500 p-7 shadow-2xl shadow-violet-950/50 sm:h-[370px] sm:w-[245px]"><div className="flex h-full flex-col justify-between"><div className="text-[10px] font-bold tracking-[.28em] text-violet-200">STORYBOOK / 01</div><div><div className="mb-3 text-xs text-violet-200/70">BOOK OF THE WEEK</div><div className="text-3xl font-black leading-none sm:text-4xl">Small<br/>habits.<br/><span className="text-cyan-200">Big change.</span></div></div><div className="text-xs text-white/50">Read • Reflect • Share</div></div></div>
      <div className="absolute left-1/2 top-1/2 h-[280px] w-[185px] -translate-x-[38%] -translate-y-[42%] rotate-[13deg] rounded-r-3xl rounded-l-md border border-white/10 bg-gradient-to-br from-cyan-950 to-cyan-600 p-6 shadow-xl sm:h-[330px] sm:w-[220px]"><div className="flex h-full flex-col justify-between"><span className="text-[9px] font-bold tracking-[.3em] text-cyan-100">DISCOVER</span><b className="text-2xl leading-none">Find your<br/>next chapter.</b><span className="text-xs text-white/50">A reader's edition</span></div></div>
      <div className="absolute bottom-3 right-4 rounded-2xl border border-white/10 bg-slate-950/80 px-4 py-3 shadow-xl backdrop-blur-xl"><div className="flex items-center gap-2 text-xs text-slate-400"><span className="grid size-7 place-items-center rounded-full bg-gradient-to-br from-violet-500 to-cyan-400 text-[10px] font-black">SB</span><span><b className="text-white">12.4k</b> readers building habits</span></div></div>
    </div>
   </section>

   <section id="discover" className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.22em] text-violet-300">Discover</p><h2 className="text-3xl font-black tracking-tight sm:text-4xl">Books worth your time.</h2><p className="mt-2 text-sm text-slate-500">Curated by readers, not algorithms alone.</p></div><span className="hidden text-sm text-slate-500 sm:block">{filtered.length} titles</span></div><div className="hide-scroll mb-7 flex gap-2 overflow-x-auto pb-1">{genres.map(g=><button key={g} onClick={()=>setGenre(g)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-xs font-bold transition ${genre===g?"border-violet-400/40 bg-violet-500/15 text-violet-200":"border-white/10 bg-white/[.03] text-slate-500 hover:text-white"}`}>{g}</button>)}</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{filtered.map((b,i)=><article key={b.id} className="panel group overflow-hidden rounded-3xl"><div className="book-cover h-64 p-5" style={{background:b.color}}><div className="flex justify-between text-[10px] font-bold tracking-[.18em] text-white/60"><span>{b.genre.toUpperCase()}</span><button onClick={()=>toggleSave(b.id)} aria-label="Save book" className="grid size-8 place-items-center rounded-full bg-black/20 backdrop-blur"><Bookmark size={15} fill={saved.includes(b.id)?"currentColor":"none"}/></button></div><div><div className="mb-3 text-xs text-white/50">STORYBOOK EDITION</div><h3 className="max-w-[180px] text-2xl font-black leading-none tracking-tight">{b.title}</h3><p className="mt-2 text-xs text-white/60">{b.author}</p></div></div><div className="p-5"><div className="flex items-center justify-between"><span className="flex items-center gap-1 text-sm font-bold text-amber-300"><Star size={14} fill="currentColor"/>{b.rating}</span><span className="text-xs text-slate-600">{b.reviews.toLocaleString()} reviews</span></div><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-500">{b.description}</p><button onClick={()=>toast(`${b.title} added to your reading queue`)} className="mt-4 w-full rounded-xl border border-white/10 bg-white/5 py-2.5 text-xs font-bold text-slate-300 hover:bg-white/10">View book</button></div></article>)}</div>{filtered.length===0&&<div className="panel rounded-3xl p-10 text-center text-slate-500">No books match that search yet. Try another title or genre.</div>}</section>

   <section id="community" className="border-y border-white/[.06] bg-white/[.012] py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="mb-8"><p className="mb-2 text-xs font-bold uppercase tracking-[.22em] text-cyan-300">Community</p><h2 className="text-3xl font-black tracking-tight sm:text-4xl">The reader feed.</h2><p className="mt-2 text-sm text-slate-500">Real reactions, thoughtful reviews and people discovering books together.</p></div><div className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]"> <div>{reviews.map(r=><article key={r.id} className="panel mb-4 rounded-3xl p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-400 text-xs font-black text-slate-950">{r.initials}</div><div><b className="text-sm">{r.user}</b><div className="text-xs text-slate-600">reviewed <span className="text-slate-400">{r.book}</span> · {r.time}</div></div><span className="ml-auto flex items-center gap-1 text-xs font-bold text-amber-300">{r.rating}.0 <Star size={13} fill="currentColor"/></span></div><p className="mt-5 text-[15px] leading-7 text-slate-300">“{r.text}”</p><div className="mt-5 flex items-center gap-5 text-xs text-slate-500"><button onClick={()=>toggleLike(r.id)} className={`flex items-center gap-1.5 hover:text-white ${liked.includes(r.id)?"text-pink-300":""}`}><Heart size={15} fill={liked.includes(r.id)?"currentColor":"none"}/>{r.likes}</button><button onClick={()=>toast("Comments are coming with the community backend.")} className="flex items-center gap-1.5 hover:text-white"><MessageCircle size={15}/>{r.comments}</button><button onClick={()=>toast("Review saved to your reading notes.")} className="ml-auto flex items-center gap-1.5 hover:text-white"><Bookmark size={15}/> Save</button></div></article>)}</div><aside><div className="panel rounded-3xl p-6"><div className="flex items-center gap-2 text-sm font-bold"><Flame className="text-orange-300" size={17}/> Trending discussion</div><h3 className="mt-5 text-xl font-black">What makes a book unforgettable?</h3><p className="mt-2 text-sm leading-6 text-slate-500">Join 342 readers discussing characters, endings and the stories they still think about.</p><button onClick={()=>toast("Discussion room is ready for the next backend step.")} className="mt-5 w-full rounded-xl bg-white py-3 text-xs font-extrabold text-slate-950">Join discussion</button></div><div className="panel mt-4 rounded-3xl p-6"><div className="flex items-center gap-2 text-sm font-bold"><Users size={17} className="text-cyan-300"/> Community pulse</div><div className="mt-5 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-white/[.035] p-4"><b className="text-2xl">12.4k</b><p className="mt-1 text-[11px] text-slate-600">readers</p></div><div className="rounded-2xl bg-white/[.035] p-4"><b className="text-2xl">3.8k</b><p className="mt-1 text-[11px] text-slate-600">reviews</p></div></div></div></aside></div></div></section>

   <section id="library" className="mx-auto max-w-7xl px-4 py-16 sm:px-6"><div className="grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><div className="noise panel rounded-[28px] p-7"><div className="flex size-12 items-center justify-center rounded-2xl bg-violet-500/15 text-violet-300"><Library/></div><h2 className="mt-5 text-2xl font-black">Your reading space.</h2><p className="mt-2 text-sm leading-6 text-slate-500">Build a personal library with Want to Read, Reading, Finished and Favorites shelves.</p><div className="mt-6 grid grid-cols-2 gap-2"><div className="rounded-2xl border border-white/5 bg-white/[.03] p-4"><b className="text-xl">{saved.length}</b><p className="text-xs text-slate-600">saved now</p></div><div className="rounded-2xl border border-white/5 bg-white/[.03] p-4"><b className="text-xl">14</b><p className="text-xs text-slate-600">finished</p></div></div><button onClick={()=>{if(!user)setAuthOpen(true);else toast("Your shelves are synced with Supabase.")}} className="mt-5 w-full rounded-xl border border-white/10 bg-white/5 py-3 text-xs font-bold hover:bg-white/10">{user?"Open my library":"Sign in to sync library"}</button></div><div className="panel rounded-[28px] p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-lime-300">This week</p><h2 className="mt-2 text-2xl font-black">Reading momentum</h2></div><div className="grid size-11 place-items-center rounded-2xl bg-lime-400/10 text-lime-300"><Flame size={20}/></div></div><div className="mt-7 flex items-end gap-2">{[35,58,45,78,64,92,72].map((h,i)=><div key={i} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-xl bg-gradient-to-t from-violet-600/60 to-cyan-300/70" style={{height:`${h}px`}}/><span className="text-[10px] text-slate-600">{["M","T","W","T","F","S","S"][i]}</span></div>)}</div><div className="mt-7 flex items-center justify-between rounded-2xl border border-white/5 bg-white/[.025] p-4"><div><p className="text-xs text-slate-600">Current streak</p><b className="text-xl">8 days 🔥</b></div><div className="text-right"><p className="text-xs text-slate-600">Goal</p><b className="text-xl">3 / 5 hrs</b></div></div></div></div></section>

   <section id="challenges" className="border-t border-white/[.06] bg-white/[.012] py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.22em] text-amber-300">Challenges</p><h2 className="text-3xl font-black tracking-tight sm:text-4xl">Make reading a game.</h2><p className="mt-2 text-sm text-slate-500">Small goals. Visible progress. Better habits.</p></div><button onClick={()=>toast("Challenge system is ready — create your profile to join.")} className="rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-xs font-bold">View all challenges</button></div><div className="mt-8 grid gap-4 md:grid-cols-3"><Challenge icon="📚" title="10 books in 2026" progress={60} meta="6 of 10 finished"/><Challenge icon="🌍" title="Read Africa" progress={40} meta="2 of 5 authors"/><Challenge icon="🧠" title="Deep reader" progress={75} meta="15 of 20 sessions"/></div></div></section>

   <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><div className="noise relative overflow-hidden rounded-[32px] border border-violet-400/20 bg-gradient-to-br from-violet-500/15 via-slate-950 to-cyan-400/10 p-8 sm:p-12"><div className="relative z-10 max-w-2xl"><div className="mb-4 flex size-11 items-center justify-center rounded-2xl bg-white/10"><Trophy size={20}/></div><h2 className="text-3xl font-black tracking-tight sm:text-4xl">Your next chapter starts here.</h2><p className="mt-3 text-sm leading-7 text-slate-400">Create a profile, save books, publish reviews and build a reading identity that grows with you.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>user?setShareOpen(true):setAuthOpen(true)} className="rounded-2xl bg-white px-5 py-3 text-sm font-extrabold text-slate-950">{user?"Share a review":"Create free account"}</button><a href="#discover" className="rounded-2xl border border-white/10 bg-white/5 px-5 py-3 text-sm font-bold">Keep exploring</a></div></div></div></section>
  </main>

  <footer className="border-t border-white/[.06] py-8"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-4 text-xs text-slate-600 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex items-center gap-2 text-slate-400"><BookOpen size={15}/> StoryBook</div><span>Read. Share. Discover. · Built for readers.</span><span>© 2026 StoryBook</span></div></footer>

  {authOpen&&<Modal title={authMode==="signin"?"Welcome back":"Create your reader profile"} close={()=>setAuthOpen(false)}><form onSubmit={submitAuth} className="space-y-4"><p className="text-sm leading-6 text-slate-500">{configured?"Use your email to access your shelves, reviews and reading streak.":"Supabase is not connected yet. Add your project keys to enable accounts."}</p><label className="block text-xs font-bold text-slate-400">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm outline-none focus:border-violet-400/50"/></label><label className="block text-xs font-bold text-slate-400">Password<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm outline-none focus:border-violet-400/50"/></label><button disabled={loading} className="w-full rounded-xl bg-white py-3 text-sm font-extrabold text-slate-950 disabled:opacity-50">{loading?"Working...":authMode==="signin"?"Sign in":"Create account"}</button><button type="button" onClick={()=>setAuthMode(authMode==="signin"?"signup":"signin")} className="w-full text-xs text-violet-300">{authMode==="signin"?"Need an account? Create one":"Already have an account? Sign in"}</button></form></Modal>}
  {shareOpen&&<Modal title="Share a book with the community" close={()=>setShareOpen(false)}><form onSubmit={submitReview} className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs font-bold text-slate-400">Book title<input required name="title" className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm outline-none"/></label><label className="block text-xs font-bold text-slate-400">Author<input required name="author" className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm outline-none"/></label></div><div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs font-bold text-slate-400">Genre<select name="genre" className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm outline-none">{genres.slice(1).map(g=><option key={g}>{g}</option>)}</select></label><label className="block text-xs font-bold text-slate-400">Rating<select name="rating" className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm outline-none">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></label></div><label className="block text-xs font-bold text-slate-400">Your review<textarea required name="text" minLength={20} className="mt-2 min-h-28 w-full rounded-xl border border-white/10 bg-white/5 px-3 py-3 text-sm outline-none" placeholder="What did this book make you think about?"/></label><button disabled={loading} className="w-full rounded-xl bg-white py-3 text-sm font-extrabold text-slate-950 disabled:opacity-50">{loading?"Publishing...":user?"Publish review":"Sign in to publish"}</button></form></Modal>}
 </div>
}

function Challenge({icon,title,progress,meta}:{icon:string;title:string;progress:number;meta:string}){return <div className="panel rounded-3xl p-5"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-white/[.04] text-xl">{icon}</span><span className="text-xs font-bold text-slate-500">{progress}%</span></div><h3 className="mt-5 font-bold">{title}</h3><p className="mt-1 text-xs text-slate-600">{meta}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-300" style={{width:`${progress}%`}}/></div></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/75 p-4 backdrop-blur-md"><div className="panel fade-up max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-[28px] p-6 sm:p-7"><div className="mb-6 flex items-start justify-between gap-4"><div><div className="mb-1 text-[10px] font-bold uppercase tracking-[.2em] text-violet-300">StoryBook</div><h2 className="text-2xl font-black">{title}</h2></div><button onClick={close} className="rounded-xl border border-white/10 p-2 text-slate-500 hover:text-white"><X size={18}/></button></div>{children}</div></div>}
